#!/bin/bash
sudo yum install java-1.8*
sudo java -version
sudo yum -y install wget
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum -y install jenkins
sudo systemctl start jenkins
sudo systemctl enable jenkins
sudo service jenkins start
sudo service jenkins status
sudo yum install tmux -y
service jenkins status
